// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalorieCounter.Models;

public partial class Activity
{
    public int ActivityPk { get; set; }

    public string ActivityTitle { get; set; }

    public int CaloriesBurned { get; set; }

    public int IntensityFk { get; set; }

    public virtual ActivityIntensity IntensityFkNavigation { get; set; }
}