// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalorieCounter.Models;

public partial class ActivityIntensity
{
    public int IntensityPk { get; set; }

    public string IntensityLevel { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();
}