// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalorieCounter.Models;

public partial class Category
{
    public int FoodCategoryId { get; set; }

    public string CategoryTitle { get; set; }

    public virtual ICollection<FoodFoodCategory> FoodFoodCategories { get; set; } = new List<FoodFoodCategory>();
}