// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalorieCounter.Models;

public partial class FoodFoodCategory
{
    public int FoodId { get; set; }

    public int FoodCategoryId { get; set; }

    public virtual Food Food { get; set; }

    public virtual Category FoodCategory { get; set; }
}