// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CalorieCounter.Models;

public partial class Food
{
    public int FoodId { get; set; }

    public string Title { get; set; }

    public int Calories { get; set; }

    public int Carbs { get; set; }

    public int Protein { get; set; }

    public int Fat { get; set; }

    public string Image { get; set; }

    public virtual ICollection<FoodFoodCategory> FoodFoodCategories { get; set; } = new List<FoodFoodCategory>();
}